"""added cir_students table

Revision ID: 6a14b8fde46d
Revises: 232606481714
Create Date: 2020-02-21 10:14:07.379403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a14b8fde46d'
down_revision = '232606481714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cir_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lasid', sa.Integer(), nullable=True),
    sa.Column('student_race', sa.String(length=50), nullable=True),
    sa.Column('student_gender', sa.String(length=25), nullable=True),
    sa.Column('student_grade', sa.Integer(), nullable=True),
    sa.Column('incident_role', sa.String(length=50), nullable=True),
    sa.Column('school_enrolled', sa.String(length=100), nullable=True),
    sa.Column('parent_notified', sa.Boolean(), nullable=True),
    sa.Column('cir_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cir_id'], ['ci_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cir_students_lasid'), 'cir_students', ['lasid'], unique=False)
    op.create_index(op.f('ix_cir_students_school_enrolled'), 'cir_students', ['school_enrolled'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cir_students_school_enrolled'), table_name='cir_students')
    op.drop_index(op.f('ix_cir_students_lasid'), table_name='cir_students')
    op.drop_table('cir_students')
    # ### end Alembic commands ###
