"""CIR Table 1.0

Revision ID: 940037b6da96
Revises: 7214fdf69ade
Create Date: 2020-01-09 12:44:35.303706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940037b6da96'
down_revision = '7214fdf69ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_inserted', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('incident_datetime', sa.DateTime(), nullable=True),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('phys_restraint', sa.Boolean(), nullable=True),
    sa.Column('police', sa.Boolean(), nullable=True),
    sa.Column('phys_harm', sa.Boolean(), nullable=True),
    sa.Column('fire_rescue', sa.Boolean(), nullable=True),
    sa.Column('dcyf', sa.Boolean(), nullable=True),
    sa.Column('risk_assessment', sa.Boolean(), nullable=True),
    sa.Column('cteam_response', sa.String(length=350), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_report_date_inserted'), 'ci_report', ['date_inserted'], unique=False)
    op.create_index(op.f('ix_ci_report_incident_type'), 'ci_report', ['incident_type'], unique=False)
    op.create_index(op.f('ix_ci_report_school_name'), 'ci_report', ['school_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ci_report_school_name'), table_name='ci_report')
    op.drop_index(op.f('ix_ci_report_incident_type'), table_name='ci_report')
    op.drop_index(op.f('ix_ci_report_date_inserted'), table_name='ci_report')
    op.drop_table('ci_report')
    # ### end Alembic commands ###
